config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  get 'users/show'

  root 'posts#index'
  devise_for :users
    resources :users, only:[:index,:show,:edit,:update] do
    	resource :relationships, only:[:create, :destroy]
    	get :follows, on: :member
    	get :followers, on: :member
    	get :favorites, on: :member
    end
	resources :posts do
		resource :favorites, only:[:create,:destroy]
    resources :comments, only:[:create,:destroy]
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	default_scope -> {order(created_at: :desc)}
	belongs_to :post
	validates :body, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :post
	validates :post, presence: true
	validates :user_id, uniqueness: {scope: :post_id}
	validates :post, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	default_scope -> {order(created_at: :desc)}
	mount_uploader :image, ImageUploader
	validates :title, presence: true
	validates :body, presence: true
	belongs_to :user
	has_many :favorites,dependent: :destroy
	has_many :comments, dependent: :destroy
	def favorited_by? user
		favorites.where(user_id: user.id).exists?
	end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: User
	belongs_to :following, class_name: User
	validates :follower_id, presence: true
	validates :following_id, presence: true
	validates :following_id, uniqueness: { scope: :follower_id}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, uniqueness: true
  mount_uploader :image,ImageUploader
  has_many :posts
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: :follower_id
  has_many :followings, through: :relationships
  has_many :inverse_follows, foreign_key: :following_id , class_name: Relationship
  has_many :followers, through: :inverse_follows
  def followed_by? user
  	inverse_follows.where(follower_id: user.id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  	protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.permit(:sign_up, keys:[:name,:email])
  		devise_parameter_sanitizer.permit(:account_update,keys:[:name,:email])
  	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params)
		@comment.user_name = current_user.name
		if @comment.save
			redirect_to post_path(params[:post_id])
		else
			redirect_to post_path(params[:post_id])
		end
	end
	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to post_path(params[:post_id])
	end
	private
	def comment_params
		params.require(:comment).permit(:user_name,:post_id,:body)
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@favorite = current_user.favorites.build(post: @post)
		if @favorite.save
			redirect_to posts_path, notice:'お気に入りに登録しました'
		else
			redirect_to posts_path, alert:'🔖に登録できません'
		end
	end
	def destroy
		@favorite = current_user.favorites.find_by!(post_id: params[:post_id])
		@favorite.destroy
		redirect_to posts_path, notice:'お気に入りを解除しました'
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only:[:show,:edit,:update,:destroy]
	before_action :correct_user, only:[:edit,:update]
	def new
		@post = Post.new
	end
	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			redirect_to posts_path
		else
			render :new
		end
	end
	def index
		@posts = Post.page(params[:page]).per(10)
	end
	def show
		@comment = Comment.new
	end
	def edit
	end
	def update
		if @post.update
			redirect_to post_path(@post.id)
		else
			render :edit
		end
	end
	def destroy
		@post.destroy
		redirect_to posts_path
	end
	private
	def set_post
		@post = Post.find(params[:id])
	end
	def post_params
		params.require(:post).permit(:title,:body,:user_id,:image)
	end
	def correct_user
		post = Post.find(params[:id])
		if current_user.id != post.user.id
			redirect_to root_path
		end
	end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		@user = User.find(params[:user_id])
		follow = current_user.relationships.build(following_id: @user.id)
		if follow.save
			redirect_to posts_path, notice: 'フォローしました'
		else
			redirect_to posts_path, alert: 'フォローできません'
		end
	end
	def destroy
		@user = User.find(params[:user_id])
		follow = current_user.relationships.find_by!(following_id: @user.id)
		follow.destroy
		redirect_to posts_path,notice: 'フォローを解除しました'
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only: [:show,:edit,:update,:favorites,:follows,:followers]
  before_action :correct_user ,only:[:edit,:update]
  def index
  	@user = User.all
  end
  def show
  end
  def edit
  end
  def update
  	if @user.update(user_params)
  		redirect_to user_path(@user.id)
  	else
  		render :edit
  	end
  end
  def favorites
  end
  def follows
  end
  def followers
  end
  private
  def set_user
  	@user = User.find(params[:id])
  end
  def user_params
  	params.require(:user).permit(:name,:body,:image)
  end
  def correct_user
    user = User.find(params[:id])
    if current_user.id != user.id
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task4th</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
    <header class="header">
  	<% if user_signed_in? %>
      <ul class="header-nav">
        <p class="header-title">ようこそ<%= current_user.name %>さん</p>
  		  <li class="header-list"><%= link_to 'ログアウト', destroy_user_session_path,method: :delete %>|</li>
        <li class="header-list"><%= link_to 'トップ', posts_path %>|</li>
        <li class="header-list"><%= link_to 'マイページ', user_path(current_user.id) %>|</li>
        <li class="header-list"><%= link_to 'ユーザー一覧',users_path %></li>|
        <li class="header-list"><%= link_to '投稿する', new_post_path %></li>
      </ul>
  	<% else %>
      <ul class="header-nav">
  		  <li class="header-list"><%= link_to '新規登録', new_user_registration_path %>|</li>
  		  <li class="header-list"><%= link_to 'ログイン', new_user_session_path %></li>
      </ul>
  	<% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="section">
	<h1 class="post-main-title">投稿編集</h1>
	<div class="content">
		<%= form_for(@post) do |f| %>
			<%= f.text_field :title,class: "post-form" %>
			<%= f.text_area :body,class: "post-form-body" %>
			<%= f.submit '保存', class: "post-form-submit"%>
		<% end %>
	<div class="delete"><%= link_to '削除', post_path,method: :delete %></div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="section">
<h1 class="post-main-title">Nekotter</h1>
	<div class="content">
	<% @posts.each do |post| %>
	<div class="post-item">
			<div class="post-user-container">
			<% if post.user.image? %>
				<%= image_tag post.user.image.url, class: "post-user-img" %>
			<% end %>
			<p class="post-name"><%= link_to post.user.name ,user_path(post.user_id) %></p>
			<p class="post-title"><%= link_to post.title, post_path(post.id)%></p>
				<% if post.image? %>
					<%= image_tag post.image.url, class: "post-img" %>
				<% end %>
			</div>
			<p class="post-body"><%= post.body %></p>
		<% if post.favorited_by? current_user %>
			<div class= "post-favo"><%= link_to 'いいね済み', post_favorites_path(post.id),method: :delete %>
				<i class="fa fa-thumbs-up" aria-hidden="true"></i></div>
				<%= post.favorites.count %>
		<% else %>
			<div class="post-favo"><%= link_to 'いいね', post_favorites_path(post.id),method: :post %>
				<i class="fa fa-thumbs-o-up" aria-hidden="true"></i></div>
				<%= post.favorites.count %>
		<% end %> 
		<% if post.user.followed_by? current_user %>
			<div class="post-follow settled"><%= link_to 'フォロー解除',user_relationships_path(post.user_id), method: :delete %></div>
		<% else %>
			<div class="post-follow"><%= link_to 'フォローする', user_relationships_path(post.user_id),method: :post %></div>
		<% end %>
	</div>
	<% end %>
	</div>
</div>
<div class="page"><%= paginate @posts %></div>

app/views/posts/new.html.erb
<div class="section">
	<h1 class="post-main-title">新規投稿</h1>
	<div class="content">
		<% if @post.errors.any? %>
			<% @post.errors.full_messages.each do |message| %>
			<p class="error"><%= message %></p>
			<% end %>
		<% end %>
		<%= form_for(@post) do |f| %>
			<%= f.text_field :title,placeholder: "タイトル",class: "post-form" %>
			<%= f.text_area :body,placeholder: "本文",class: "post-form-body" %>
			<p>写真を投稿する</p>
			<%= f.file_field :image, class: "post-form-img" %>
			<%= f.submit '投稿', class: "post-form-submit"%>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="section">
	<div class="content">
		<div class="show-name"><%= link_to @post.user.name ,user_path(@post.user_id)%><%= @post.user.email %></div>
		<h1 class="show-title"><%= @post.title %></h1>
			<% if @post.image? %>
				<%= image_tag @post.image.url, class: "post-img" %>
			<% end %>
		<div class="show-body"><%= @post.body %></div>
		<% if current_user.id == @post.user_id %>
			<%= link_to '編集', edit_post_path, class: "edit" %>
		<% end %>
	</div>
		<div class="comment-area">
			<% @post.comments.each do |comment| %>
				<P><%= comment.user_name %></P>
				<p><%= comment.body %></p>
			<% if current_user.name == comment.user_name %>
					<%= link_to '削除', post_comment_path(@post,comment), method: :delete %>
			<% end %>
			<% end %>
			<%= form_for [@post, @comment] do |f| %>
				<%= f.text_area :body, class: "comment-form" %>
				<%= f.submit 'コメント', class: "comment-submit"%>
			<% end %>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="section">
	<div class="content">
	<h1 class="edit-name"><%= @user.name %></h1>
	<%= form_for(@user) do |f| %>
		<p>名前</p>
		<%= f.text_field :name , class: "user-form"%>
		<P>トップ画像</P>
		<%= f.file_field :image %>
		<p>プロフィール</p>
		<%= f.text_area :body , class: "user-form-body" %>
		<%= f.submit '保存', class: "user-form-submit" %>
	<% end %>
	</div>
</div>

app/views/users/favorites.html.erb
<div class="section">
	<div class="user-show">
		<h1 class="user-name"><%= @user.name %></h1>
		<p class="user-favo">いいね
			<i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
			<%= @user.favorites.count %></p>

		<% if @user.favorites.empty? %>
			<p>まだお気に入りされた投稿はありません</p>
		<% end %>
		<% @user.favorites.map{|f| f.post}.each do |post| %>
			<p><%= post.user.name %></p>
			<P><%= link_to post.title, post_path(post) %></P>
			<p><%= post.body %></p>
		<% end %>
	</div>
</div>

app/views/users/followers.html.erb
<div class="section">
	<div class="user-show">
		<h1 class="user-name"><%= @user.name %>/フォロワー一覧</h1>
		<div class="user-favo-follow">
		<p class="user-item">投稿数<%= @user.posts.count %></p>
		<p class="user-item"><%= link_to 'いいね' ,favorites_user_path(@user) %><%= @user.favorites.count %></p>
		<p class="user-item"><%= link_to 'フォロー' ,follows_user_path(@user) %><%= @user.followings.count %></p>
		<p class="user-item"><%= link_to 'フォロワー',followers_user_path(@user) %><%= @user.followers.count %> </p>
		</div>
		<% @user.followers.each do |follow| %>
		<div class="follow-container clearfix">
			<% if follow.image? %>
				<%= image_tag follow.image.url, class: "follow-img" %>
			<% else %>
				<div class="alt">画像が<br>ありません</div>
			<% end %>
			<div class="other-user"><%= link_to follow.name, user_path(follow) %></div>
			<% if follow.followed_by? current_user %>
			<div class="user-follow settled"><%= link_to 'フォロー解除', user_relationships_path(follow),method: :delete %></div>
		<% else %>
			<div class="user-follow"><%= link_to 'フォロー', user_relationships_path(follow),method: :post %></div>
		<% end %>
		</div>
	<% end %>
	</div>
</div>

app/views/users/follows.html.erb
<div class="section">
	<div class="user-show">
		<h1 class="user-name"><%= @user.name %>/フォロー一覧</h1>
		<div class="user-favo-follow">
			<p class="user-item">投稿数<%= @user.posts.count %></p>
			<p class="user-item"><%= link_to 'いいね' ,favorites_user_path(@user) %><%= @user.favorites.count %></p>
			<p class="user-item"><%= link_to 'フォロー' ,follows_user_path(@user) %><%= @user.followings.count %></p>
			<p class="user-item"><%= link_to 'フォロワー',followers_user_path(@user) %><%= @user.followers.count %> </p>
		</div>
		<% @user.followings.each do |follow| %>
		<div class="follow-container clearfix">
		<% if follow.image? %>
			<%= image_tag follow.image.url,class: "follow-img" %>
		<% else %>
			<div class="alt">画像が<br>ありません</div>
		<% end %>
		<div class="other-user"><%= link_to follow.name, user_path(follow) %></div>
		<% if follow.followed_by? current_user %>
			<div class="user-follow settled"><%= link_to 'フォロー解除', user_relationships_path(follow),method: :delete %></div>
		<% else %>
			<div class="user-follow"><%= link_to 'フォロー', user_relationships_path(follow),method: :post %></div>
		<% end %>
	    </div>
	<% end %>
	</div>
</div>

app/views/users/index.html.erb
<div class="section">
	<div class="user-show">
		<h1>ユーザー一覧</h1>
		<% @user.each do |user| %>
		<div class="user-index-item">
		<% if user.image? %>
			<%= image_tag user.image.url, class: "follow-img" %>
		<% else %>
			<div class="alt">画像が<br>ありません</div>
		<% end %>
		<div class="other-user"><%= link_to user.name, user_path(user) %></div>
			<% if user.followed_by? current_user %>
				<div class="user-follow settled"><%= link_to 'フォロー解除', user_relationships_path(user),method: :delete %></div>
			<% else %>
				<div class="user-follow"><%= link_to 'フォロー', user_relationships_path(user),method: :post %></div>
			<% end %>
		</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<div class="section">
	<div class="user-show">
		<div class="profile clearfix">
		<h1 class="user-name"><%= @user.name %></h1>
		<% if @user.image? %>
			<%= image_tag @user.image.url, class: "user-img" %>
		<% else %>
			<P>画像がありません</P>
		<% end %>
		<p class="user-body"><%= @user.body %></p>
		<% if current_user.id == @user.id %>
			<%= link_to 'プロフィールを編集する', edit_user_path(@user),class: "user-edit" %>
		<% end %>
		</div>
		<div class="user-content">
			<div class="user-favo-follow">
			<div class="user-item">投稿数<%= @user.posts.count %></div>
			<div class="user-item"><%= link_to 'いいね' ,favorites_user_path(@user) %><%= @user.favorites.count %></div>
			<div class="user-item"><%= link_to 'フォロー' ,follows_user_path(@user) %><%= @user.followings.count %></div>
			<div class="user-item"><%= link_to 'フォロワー',followers_user_path(@user) %><%= @user.followers.count %></div>
		</div>
			<div class="user-post">
			<% @user.posts.each do |post| %>
				<p><%= link_to post.title, post_path(post.id) %></p>
				<p><%= post.body %></p>
			<% end %>
			</div>
		</div>
	</div>
</div>